#!/bin/bash

# Get the ZIP file path from the command-line argument
zip_file=$1

# Loop through the list of files inside the ZIP file
while read -r name; do
    # Check if the file matches the desired pattern (inside data directory and ends with _foxml_atomzip.zip)
    if [[ $name == *data/*_foxml_atomzip.zip ]]; then
        # Extract the COLLECTIONNAME:PID from the file name
        collection_pid=$(basename "$name" | sed 's/_foxml_atomzip.zip//; s/_/:/')
        
        # Call the drush command to create an islandora bag using the COLLECTIONNAME:PID as an argument
        # The command suppresses output to /dev/null using &> /dev/null
        drush @dsu --user=1 create-islandora-bag object $collection_pid &> /dev/null
    fi
done < <(unzip -l "$zip_file" | awk '/data/ && /_foxml_atomzip.zip/ { print $NF }')
